### ISSUE TITLE
Printable version of the site

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/fullPage.js#1283]
Right now only the active section gets printed. 
Ideally the whole site should be able to be printed at once.

**Comment by latwelve** [comment]
The screen closes when I try to print - it appears the url when it has sections linked in it effects the default print window and closes it. Have you experienced this as well? Is there a work around for now?

**Comment by alvarotrigo** [comment]
> The screen closes when I try to print

Sorry I can not reproduce it in [the demo page](http://alvarotrigo.com/fullPage/). Probably not related with fullpage.js?

**Comment by latwelve** [comment]
Speedy! fair point actually neither can I... let me see if I can find something reproducible :).

**Comment by eystein** [comment]
I added this to my print.css, overriding most of the inline styles from fullpage.js. Now it prints everything.

```css
/* Override javascript inline styles */
html,
body {
    overflow: visible !important;
    height: auto !important;
}

.fullpage-wrapper {
    height: auto !important;
    transform: none !important;
    transition: none !important;
}

.fp-section {
    height: auto !important;
}

.fp-slidesContainer {
    width: auto !important;
    transition: none !important;
    transform: none !important;
}

.fp-slides,
.fp-slides * {
    position: static !important;
}

.fp-slide {
    width: auto !important;
}
```

**Comment by latwelve** [comment]
I fixed my issue too... it was to do with the hashs in the url... not sure why sorry but clearing it first made print reliable for me:

			window.location.hash="";
			window.print();

**Comment by alvarotrigo** [comment]
I was trying to force the page break after each section or slide with:

```css
    .fp-section{
        page-break-after: always !important;
    }
    .fp-slide{
        page-break-after: always !important;
    }
```

But I never managed to see it working properly in Chrome.
