### ISSUE TITLE
fp-auto-height css/scss missing

### ISSUE THREAD

**Issue by jessetaverne** [alvarotrigo/fullPage.js#1496]
Hey there,

Like everyone else here i'll start of with some praise.
The plugin is simply amazing!

Not sure if this is the right place to mention this, as i'm not very into github:

I was going to mention the fp-auto-height function wasn't working properly, but of course, it is.
The reason it didn't out of the box for me was that the required CSS didn't come with the plugin.

As you mentioned at #1263 the auto-height works well with the CSS.

The latest master i pulled was v2.7.1, in which neither the css nor the scss files have the following:

```css
.fp-auto-height.fp-section,
.fp-auto-height .fp-slide,
.fp-auto-height .fp-tableCell{
    height: auto !important;
}
```

They're also still at v2.6.6.

Hope this helps, maybe i overlooked something though - in that case sry, and can you tell me what i missed?
