### ISSUE TITLE
Fade effect on slides

### ISSUE THREAD

**Issue by Seb33300** [alvarotrigo/fullPage.js#1625]
Hi,

Is it possible to set a fade effect on slide change? (not on section change)

Thanks

**Comment by alvarotrigo** [comment]
Nop. This is a scrolling plugin.

**Comment by alvarotrigo** [comment]
This is now possible with the [Fading Effect Extension](http://alvarotrigo.com/fullPage/extensions/fadingEffect.html).
Assured compatibility with future releases of fullpage.js.

**Comment by Seb33300** [comment]
Awesome. Thanks!

**Comment by soutomario** [comment]
You can add a class child-slide, to the section that will have slides inside and apply this CSS:

```CSS
		.child-slide .fp-slidesContainer {
			width: 100% !important;
			position: relative;
		}
		.slide {
			width: 100% !important;
			position: absolute;
			opacity: 0 !important;
			pointer-events: none !important;
			transition: 1s ease-in-out;
		}
		.slide.active {
			opacity: 1 !important;
		}
```
