### ISSUE TITLE
Bootstrap Modal

### ISSUE THREAD

**Issue by dngretsch** [alvarotrigo/fullPage.js#1643]
Hello - Im trying to enable the fullpage.js ONLY in a bootstrap modal window. How is this achievable by toggling the 

`autoScrolling: false, `

and also using css
```css
body.modal-open {
    overflow: hidden !important;
}
````
Is this possible?
