### ISSUE TITLE
Hide navigation in one section

### ISSUE THREAD

**Issue by Eldar88** [alvarotrigo/fullPage.js#1651]
Hi there! Thanks for this, I'd like to know if it's possible to "hide" the navigation dots in a particular section of my fullpage, thanks

**Comment by alvarotrigo** [comment]
Just use CSS for it. You can use a callback to add or remove a class or make use the of the class added to the body element of the site:

For example:

```css
body.fp-viewing-secondPage-0 #fp-nav{
    display:none;
}
```
