### ISSUE TITLE
Custom page height

### ISSUE THREAD

**Issue by ZsharE** [alvarotrigo/fullPage.js#1716]
Hi,

Is it possible to have different section heights, but at least 100% ?
For example i want all the sections to be at least 100% height, but if the content of a section is bigger than 100% height i want to be able to scroll (that section).
Also is it possible to remove the scroll to section event when scrolling ? I don't mind if i click on navigation dots or menu links.

Thanks !

Edit: To prevent scrolling i used autoScrolling: false, and also i used height auto for every section:

```css
.fp-section,
.fp-slide,
.fp-tableCell{
    height: auto !important;
}
```
