### ISSUE TITLE
Responsive auto-height

### ISSUE THREAD

**Issue by panczarny** [alvarotrigo/fullPage.js#1852]
Hi,
how can I enable responsive auto-height (add class 'fp-auto-height')?
E.g. under 900px make each ".section" (or selected ones) auto-height.

Thanks!

**Comment by alvarotrigo** [comment]
I would do some conditional CSS like this:

```css
.fp-responsive #contact-section,
.fp-responsive #contact-section .fp-slide,
.fp-responsive #contact-section .fp-tableCell{
    height: auto !important;
}
```

The `fp-responsive` class is one of [the state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) added by fullpage.js.

I'll mark it as an enhancement in any case. It is a nice feature to have.
