### ISSUE TITLE
Hiding navigation in a certain section or slides

### ISSUE THREAD

**Issue by dtrinh50** [alvarotrigo/fullPage.js#1909]
I am using the dot navigation system, but I want to hide the dot navigation system and just use the arrows on slides. Is there a solution for this?

**Comment by alvarotrigo** [comment]
Hide it using CSS or javascript:

```css
.fp-viewing-SECTION-SLIDE #fp-nav{
   display:false
}
````

Check [this video](https://www.youtube.com/watch?v=qiCVPpI9l3M) for more info about how to use the state class.
