### ISSUE TITLE
Overflow on Firefox

### ISSUE THREAD

**Issue by miamis** [alvarotrigo/fullPage.js#1924]
Hello,

First, thx for this awesome plugin.

I'm having a trouble on Firefox with "overflows". (works fine on Chrome)
I use transform:scale() on my background to animate it, but when this background scales, it comes out of its section and exceed on the adjacent sections.

Here is my HTML 

```html
	<div class="section" id="section1">
		<div class="bg"></div>
	</div>
```

Here is my CSS
```css
.section {
	overflow-x :hidden;
	overflow-y: hidden;
}
`
`#section1 .bg {
	width: 100%;
	height: 100%;
	display: block;
	position: absolute;
	top:0;left:0;
	z-index: -2;
	background: url(../img/bg-people.jpg) no-repeat center center;
	background-size: cover;
    animation: bganimate infinite 20s linear forwards;
    -webkit-animation: bganimate infinite 20s linear forwards;
    -moz-animation: bganimate infinite 20s linear forwards;
}
```

Thx for help
