### ISSUE TITLE
bug with background attachement:fixed  and scrolloverflow:true

### ISSUE THREAD

**Issue by Nyanou** [alvarotrigo/fullPage.js#2171]
Hello, when i used the scroll overflow with a normal background it worked well, but when i added the background attachement:fixed to my background css (to get a kind of parallax effect when scrolling through sections) it started to bug and to not display the backgrounds.
 
the script
```javascript
		$(document).ready(function() {
			$('#fullpage').fullpage({
				verticalCentered: false,

				//to avoid problems with css3 transforms and fixed elements in Chrome, as detailed here: https://github.com/alvarotrigo/fullPage.js/issues/208
				css3:false,

				responsiveHeight: 567,

				sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE', 'whitesmoke', '#ccddff'],
				anchors: ['firstPage', 'secondPage', '3rdPage', '4thPage'],
				menu: '#menu',

				scrollingSpeed: 1700,

				scrollOverflow: true,
				scrollOverflowOptions: {
					scrollbars: true,
			        mouseWheel: true,
			        hideScrollbars: false,
			        fadeScrollbars: false,
			        disableMouse: true
				}
			});
		});
```
the css

```css
.section{
		text-align:center;
	}


	/* Backgrounds will cover all the section
	* --------------------------------------- */
	#section0,
	#section1,
	#section2,
	#section3{
		background-size: cover;
		background-attachment: fixed;
		background-position: center center;
	}

	/* Defining each sectino background and styles
	* --------------------------------------- */
	#section0{
		background-image: url(imgs/bg1.jpg);
		padding: 6% 0 0 0;
	}
	#section1{
		background-image: url(imgs/bg2.jpg);
		padding: 6% 0 0 0;
	}
	#section2{
		background-image: url(imgs/bg3.jpg);
		padding: 6% 0 0 0;
	}
	#section3{
		background-image: url(imgs/bg4.jpg);
		padding: 6% 0 0 0;
	}
```
Thanks for your help
