### ISSUE TITLE
Problem with setResponsive method

### ISSUE THREAD

**Issue by daviddelusenet** [alvarotrigo/fullPage.js#2612]
Hi,

Currently I'm trying to use Fullpage on a website I'm building. At the moment I've two questions:

First of all, is it possible to disable Fullpage on screens bigger than 640px and enable it on smaller screens than 640px? 

I know about the existence of the `responsiveWidth` option, but this option only allows me to disable Fullpage on screens smaller than the stated value. 

For now I'm using the `setResponsive` method to enable/disable Fullpage. I'm doing this like so:

```
setFullpageResponsive() {

  if (window.innerWidth > 639) {
    $.fn.fullpage.setResponsive(true);
  } else {
    $.fn.fullpage.setResponsive(false);
  }

}
```

Only when I use this method the inline styles of Fullpage don't get removed. This means normal scrolling is enabled but the sections still have the height Fullpage gave them. So my question is: is this supposed to be like this or is this a bug?

Thanks in advance!

**Comment by alvarotrigo** [comment]
> First of all, is it possible to disable Fullpage on screens bigger than 640px and enable it on smaller screens than 640px?

You have been answered:
https://github.com/alvarotrigo/fullPage.js/issues/2517#issuecomment-286732681

Regarding the auto height feature, you can apply it whenever you want by just using CSS:
```css
.fp-section,
.fp-slide,
.fp-tableCell {
    height: auto !important;
}
```

So, you can add a class to the body whenever you need and apply it as you wish.

**Comment by daviddelusenet** [comment]
Thanks!

**Comment by alvarotrigo** [comment]
You can even use fullpage.js classes for your last question regarding  auto height:

```css
body:not(fp-responsive) .fp-section,
body:not(fp-responsive) .fp-slide,
body:not(fp-responsive) .fp-tableCell {
    height: auto !important;
}
```
