### ISSUE TITLE
Body padding / bordered

### ISSUE THREAD

**Issue by reeslo** [alvarotrigo/fullPage.js#2735]
I would have a white border arround the body, I've tried to force body pading without success.

So I've added a border to my body (1.375rem), top off sections are well positioned at 1.375rem, when sliding too.

But the section height is 1.375rem bigger so the 1.375rem of the bottom are hidden. I don't found similare cases, there is possible to do that whith fullpage.js ?

For the moment I've fixed the height with the option paddingBottom: '1.375rem'.

Thanks

**Comment by alvarotrigo** [comment]
Just make use of the fullpage.js options `paddingTop` and `paddingBottom` combined with your soultion.

You could do something like this:

```css
body{
   border-right: 20px solid #fff;
   border-left: 20px solid #fff;
}
body:before, 
body:after {
    background: none repeat scroll 0 0 #fff;
    content: "";
    height: 20px;
    left: 0;
    position: fixed;
    right: 0;
    z-index: 666555;
    padding: 0;
}
body:after {
    bottom: 0;
}
```
[Online demo](http://jsfiddle.net/97tbk/1888/) Notice how the scrollOverflow section doesn't hide the content behind the border. The scroll bar starts and end limited by the paddings.
