### ISSUE TITLE
Help: Video Overlay

### ISSUE THREAD

**Issue by gokkstudio** [alvarotrigo/fullPage.js#2761]
Hello, can someone please help me with video overlay thing.

I got: 

```css
#myVideo{
	position: absolute;
	right: 0;
	bottom: 0;
	top:0;
	right:0;
	width: 100%;
	height: 100%;
	background-size: 100% 100%;
 	background-color: black; /* in case the video doesn't fit the whole page*/
  	background-image: /* our video */;
  	background-position: center center;
  	background-size: contain;
   	object-fit: cover; /*cover video background */
   	z-index:3;
}
```

...and I made an overlay (it works fine)
```css
  .overlay {
    position: relative;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.5);
    top: 0;
    left: 0;
    z-index:4;
   }
```
problem is when scrolling back to video section, overlay is not showing until scrolling is done.

Thanks
