### ISSUE TITLE
Set verticalCentered for One Section

### ISSUE THREAD

**Issue by cgidds** [alvarotrigo/fullPage.js#2977]
On a seven section site, I'm using `verticalCentered: false`; however, I'd like to set it to true for a specific section or anchor. Is there a way to accomplish this without reinventing the wheel?

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2273

Just use CSS to turn it off:

``` css
#mySection .fp-tableCell{
   vertical-align: top;
}
```
