### ISSUE TITLE
responsive max-width not working

### ISSUE THREAD

**Issue by startum** [alvarotrigo/fullPage.js#3113]
I'm using CSS Grid with fullpage.js. When styling responsive I can only get min-width to work and not max-width. 

I'm a newbie to js so I'm sure I'm missing something. Below is my code:

```html
<script type="text/javascript">
$(document).ready(function(){
		$('#wrapper').fullpage({
            sectionsColor: ['#7c5fc4', '#000', '#fff', '#000', '#fff', '#000', '#fff', '#000', '#fff'],
            css3: true,
            responsiveWidth: 960,

        });
	});
	</script>
```
CSS:
```css
@media only screen and (max-width: 960px) {
          .container-grid1{
                  grid-template-columns: 1fr 1fr 1fr 1fr;
                  grid-template-rows: 50px 60px 50px 100px 100px 40px 40px 50px 100px;
          }
          .item-code{ grid-column: 1 / 2; grid-row: 1 / 1; color: #fff;}
          .item-mission{ grid-column: 3 / 3; grid-row: 3 / 4;}
          .item-title1{ grid-column: 3 / 3; grid-row: 4 / 4;}
          .item-title2{ grid-column: 3 / 3; grid-row: 5 / 5; color: #fff;}
}
```
