### ISSUE TITLE
text from section can be seen when the page is refreshed

### ISSUE THREAD

**Issue by PratyushMaheshwari** [alvarotrigo/fullPage.js#3131]
Hi, 
Im facing an issue that the text can be seen from the slide section while I'm refreshing the website for a fraction of seconds.

Apply the following to the CSS : 

```css
#aad{
  position: absolute;
font-family: prestige elite std;
font-size: 24pt;
top: 25%;
left: 4%;
 text-transform: uppercase;
 color: white;
}

#style1{
position: absolute;
border: 0.4pt solid white;
width: 960px;
top: 30%;
left: 4%;
}
```

Thank you.
