### ISSUE TITLE
Set a fixed background image with scrollbar true

### ISSUE THREAD

**Issue by glucee** [alvarotrigo/fullPage.js#3141]
### Description
I want to set a fixed background image, and only slide the texts.
I set the scrollbar to true, and find the background image sliding with the text, which I want to keep the background image fixed.
If I set scrollbar to false, the background image is fixed then.
My question is how to set a fixed background image when the scrollbar is true?

### Link to isolated reproduction with no external CSS / JS
```css
	.bg{
		background-image: url(img/join.jpg); 
		background-position: center;
    	background-size:cover;
		height: 100%;
	}

<div class="bg">
<div id="fullpage">
	<div class="section " id="section0">
         </div>
          <div class="section" id="section1">
		<div class="slide" id="slide1" data-anchor="slide1">
                <div class="slide" id="slide2" data-anchor="slide2">
           </div>
</div>
</div>
```
### Steps to reproduce it
1. copy .bg style to css
2. use bg div to wrap the fullpage div
3. set scrollbar to true and see the outcome

### Versions 
Chrome 64
Windows 10
