### ISSUE TITLE
CSS blend mode disabled when fullPage is enabled

### ISSUE THREAD

**Issue by zerinoid** [alvarotrigo/fullPage.js#3288]
### Description
If a blend mode is applied in a DIV inside fullPage's containers, color ceases to "interact" with body background after fullPage's code is applied.

If the background is applied to a intermediary DIV inside fullPage's main DIV then color interaction is estabilished. If you comment out fullPage's code interaction is re estabilished also.

I need the background to be static, so it need to be in BODY and not on a DIV.

links for both ocasions below

### Link to isolated reproduction with no external CSS / JS

body background
https://codepen.io/zerino/pen/MXRvbb

intermediary background
https://codepen.io/zerino/pen/mKgMjN

### Steps to reproduce it

1. Load a background in a page's body
2. apply blend mode (difference) on a div inside a .section div
3. enable fullPage code

### Versions 
Firefox and Chrome, Mac OSX 10.11 and Windows 10.

**Comment by zerinoid** [comment]
and here is the page I'm coding as well http://18.218.52.114
if it's usefull.

**Comment by alvarotrigo** [comment]
Sounds like a browsers issue and not a fullpage.js one. 
You've gotta be careful when using fixed stuff together with css3 translations.

## Solution 1:

- Remove the fixed background from the body
- Apply it to all sections

```css
.section{
    background-image: url("https://static.vecteezy.com/system/resources/previews/000/101/237/non_2x/free-abstract-background-11-vector.jpg");
  background-size: cover;
  background-attachment: fixed;
  background-position: center center;
}
```

- Then use the fullpage.s option `css3:false`

## Solution 2
- Remove the fixed background from the body
- Apply it to the fullpage wrapper

```css 
.fullpage-wrapper{
  background-image: url("https://static.vecteezy.com/system/resources/previews/000/101/237/non_2x/free-abstract-background-11-vector.jpg");
  background-size: cover;
  background-attachment: fixed;
  background-position: center center;
}
``` 
- Use the fullpage option `css3: false`
