### ISSUE TITLE
Overwrite arrows style and localization of navigationTooltips

### ISSUE THREAD

**Issue by TWDbag** [alvarotrigo/fullPage.js#3591]
First I would like to change the style (colour) of the arrows.
```
.fp-controlArrow.fp-prev {
  left: 50px;
  color: blue;
}
```
And it's not working, so I think I am doing something wrong. I tried modifying the colour directly in the plugin and unfortunately I can't do that.
*Also is there a way to change the navigational dots (`navigation:` and `slidesNavigation:`) colour as well?

Second thing I want to do is to localize the text in the navigationTooltips. Depending on which lang is used.

Edit: And also to change the text colour of navigationTooltips. Is there a way?

**Comment by alvarotrigo** [comment]
For the arrows you'll have to overwrite the color border. 
You can see how they are defined in the css file in here https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.css#L73

```css
.fp-controlArrow.fp-prev {
    left: 15px;
    width: 0;
    border-width: 38.5px 34px 38.5px 0;
    border-color: transparent #fff transparent transparent;
}
.fp-controlArrow.fp-next {
    right: 15px;
    border-width: 38.5px 0 38.5px 34px;
    border-color: transparent transparent transparent #fff;
}
```

So just use this for example for the `next` arrow:

```css
    border-color: transparent transparent transparent blue;
```

> Also is there a way to change the navigational dots (navigation: and slidesNavigation:) colour as well?

Sure. It is all about CSS. Just check [the stylesheet](https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.css) and overwrite whatever you want.

But that's a matter of CSS more than about fullPage.js. 
If you have troubles doing that I would recommend you asking about CSS in other places such as stackoverflow.com where they'll be able to help you much better.
