### ISSUE TITLE
Margin around section

### ISSUE THREAD

**Issue by elephantux** [alvarotrigo/fullPage.js#3627]
How to create margin space around all of sections? I want to create something look like on cards.

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2735

Another solution:
https://jsfiddle.net/alvarotrigo/Lv0rwtxa/10/

**Comment by elephantux** [comment]
This is not the best solution. In example above padding around page but I need margin around **each** section. Section cards must scroll with space between each other.

**Comment by alvarotrigo** [comment]
It is all about CSS.
Nothing to do with fullpage.js :)

https://jsfiddle.net/alvarotrigo/Lv0rwtxa/17/


```css
body {
    margin: 0 20px !important;
}
body:before,
body:after {
    background: none repeat scroll 0 0 #fff;
    content: "";
    height: 20px;
    left: 0;
    position: fixed;
    right: 0;
    z-index: 666555;
    padding: 0;
}

.section {
    top: auto;
    bottom: 0;
    box-sizing: border-box;
}

body:after {
    bottom: 0;
}
.my-content{
  height: calc(100% - 40px);
}

.my-content:nth-child(1){
  background:red;
}
```


```html
<div id="fullpage">
    <div class="section">
        <div class="my-content">
            Section 1
        </div>
    </div>
    <div class="section">
        <div class="my-content">
            Section 2
        </div>
    </div>
    <div class="section">
        <div class="my-content">
            Section 3
        </div>
    </div>
</div>
```


```js
new fullpage('#fullpage');
```
