### ISSUE TITLE
change color of navigation dots depending on section background

### ISSUE THREAD

**Issue by rslcdmc** [alvarotrigo/fullPage.js#3662]
Hi,
i would like to change the color of the dots, depending on the section background.
Let's say I have an extra class "dark" for the section, which means there is a dark background.
In this case, I want to have the dots white instead of black.

How would I achieve that?

**Comment by alvarotrigo** [comment]
Easy! :)
You can make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

Same you can apply for changing the color of the nav. For example:

```css
.fp-viewing-section1 #fp-nav ul li a span{
     background: red;
}
.fp-viewing-section2 #fp-nav ul li a span{
     background: blue;
}
```

**Comment by ananyalohani** [comment]
I think you meant `.fp-viewing-1`, `.fp-viewing-2` and not `.fp-viewing-section-1`. Just mentioning this to prevent confusion in the future :)

**Comment by alvarotrigo** [comment]
> I think you meant `.fp-viewing-1`, `.fp-viewing-2` and not `.fp-viewing-section-1`. Just mentioning this to prevent confusion in the future :)

That depends on the anchors you select for your sections.
But yeah, those would be the default ones if you do not use the attribute `data-anchor` on your sections or the fullpage option `anchors`. 

Thanks for pointing that out @ananyalohani ! 👍

**Comment by sevilgenysf** [comment]
I want to change navigation color in reactjs

**Comment by alvarotrigo** [comment]
> I want to change navigation color in reactjs

Sure no problem. No matter what technology you use, you'll be able to do so by overwriting the CSS associated with them.
Here's an example:
https://codepen.io/alvarotrigo/pen/bGoxveg

```css
/* Overwriting fullPage.js 
* navigation bullets' color
*/
#fp-nav ul li a span, 
.fp-slidesNav ul li a span{
  background: red;
}
```
