### ISSUE TITLE
scrollOverflow + Video Background 

### ISSUE THREAD

**Issue by Minchko** [alvarotrigo/fullPage.js#3946]
Hi Álvaro, 

I haven't any success on writing my website page with : scrollOverflow:true & the videobackground's. 

The video background haven't any scales or the text doesn't fit in the section or the text doesn't scroll, this is the results depending of my test

I load the lastet version of full page, I have a licence key and I looked on the issues like the #35, without any respons. 

Have you an idea ? I saved a litght writing version, could you give a look please ? 

Thank you, 
[test scrolloverflow+videobgd.html.zip](https://github.com/alvarotrigo/fullPage.js/files/4420548/test.scrolloverflow%2Bvideobgd.html.zip)

Benjamin

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by Minchko** [comment]
Thank you for your return and your back up, 

Sorry I believed to do well with this ligth .html files

But now : 

Here, a link : https://jsfiddle.net/Minchko/1a3yr7ue/23/

**Comment by alvarotrigo** [comment]
Please make sure your jsfiddle or codepen works. Right now there's nothing working there.

**Comment by Minchko** [comment]
Navré 

Here https://jsfiddle.net/Minchko/1a3yr7ue/52/ ? 
https://jsfiddle.net/Minchko/1a3yr7ue/53/#&togetherjs=O9keSFRjN6

**Comment by alvarotrigo** [comment]
That's not yet working.
See the [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp) links I postet before. If fullpagejs is not working then you are not doing it right :)

**Comment by Minchko** [comment]
Aye ! for sure, I didn't link the well url link to fullpage.js by UNPKG :) 

Sorry to take your time by my DIY-covid-time 

So, now that's exactly the same in my compu :

The video is in scale, the text is inside the div, when I'm sweat with the mouse I saw the scrollbar move but the text doesn't move across

https://jsfiddle.net/Minchko/1a3yr7ue/77/

**Comment by alvarotrigo** [comment]
FullPage.js won't generate an internal scrollbar for the section with the text unless you stop using `position:absolute` for it.

I would recommend you to use `position:absolute` and `z-index:0;` for your video and leave the text as normal.

The solution is this:

```js
  var myFullpage = new fullpage('#fullpage', {
      verticalCentered: true,
      scrollOverflow: true,
      afterRender: function() {
          fixVideoBackgrounds();
      }
  });

  function fixVideoBackgrounds() {
      var wrap = '.fp-scrollable';
      fp_utils.$(wrap).forEach(function(item) {
          var video = $('video', item)[0];
          if ((fp_utils.$('.fp-scrollable', item).length || fp_utils.hasClass(item, 'fp-scrollable')) &&
              video != null) {
              item.parentNode.insertBefore(video, item.parentNode.firstChild);

          }
      });
  }
```

Having this css for the video:
```css
#myVideo{
  position: absolute;
  right: 0;
  bottom: 0;
  top:0;
  right:0;
  width: 100%;
  height: 100%;
  background-size: 100% 100%;
  background-color: black; /* in case the video doesn't fit the whole page*/
  background-image: url(http://inserthtml.com/demos/javascript/background-videos/flowers.mp4);
  background-position: center center;
  background-size: contain;
  object-fit: cover; /*cover video background */
  z-index: 0;
  
}
``` 

And nothing special for the text.

Reproduction online:
https://jsfiddle.net/t3afy95k/1/
