### ISSUE TITLE
CSS Alternative

### ISSUE THREAD

**Issue by pratikkabade** [alvarotrigo/fullPage.js#4475]
### Description

Whats the advantage of [fullPage.js](https://github.com/alvarotrigo/fullPage.js) vs plain `CSS`

```css
.fullpage {
    display: flex;
    overflow: auto;

    width: 100%;
    height: 100%;

    flex: none;
    flex-flow: column nowrap;
    scroll-snap-type: y mandatory;
}

.fullpage > div {
    scroll-snap-align: center;
    flex: none;
    height: 100%;
}
```

example-[link](https://fullpagecss.netlify.app/)
