### ISSUE TITLE
Scrolling trough slides causes page refresh and complete crash on newer iPhones (both Safari and Chrome)

### ISSUE THREAD

**Issue by kovinet** [alvarotrigo/fullPage.js#4548]
### Description

We have been having HUGE problems with these script on latest iPhones. While everything works fine on desktop and on Android devices, as well as on some older iPhones (tested on iPhone 7, iPhone 11, IPhone SE) the site completely breaks on iPhone 14 after trying to scroll. What happens is that when trying to go to slide next slide browser tries to refresh the page instead and then it completely crashes.  

We have tried removing some content like images, in this case it is possible to scroll like 3 or 4 slides and then the problem repeats, making the page completely unusable on these devices.

I have been trying to isolate the problem for hours and it is hard, because I don't own new iPhone and it works on all devices I own. But the problem has been reproduced on at least 4 iPhones, where page completely crashes when trying to scroll.

### Versions 
iPhone 14 (Safari and Chrome), reproduced also on some other iPhones, while working on most older ones

**Comment by kovinet** [comment]
After doing more extensive testing I am starting to notice that the problem lies somewhere in CSS. 
When I remove all of my own CSS and just leave `fullpage.css` it seems to work.

**Comment by alvarotrigo** [comment]
Interesting 🤔 
It'd be nice to know exactly which styles are the ones interfering with it.

Perhaps removing part of them multiple times until you figure out which can be the one creating the issue?

**Comment by kovinet** [comment]
It must be some really weird bug and it only happens on some iPhones, while working perfectly on iPad, Desktop Chrome, Android phones. 

Here is video screencast of broken experience on iPhone 14: https://www.screencast.com/t/2kwzeR0JwR4q  

And how it is working perfectly on Android: https://www.screencast.com/t/v4EooCbjJ  

By now I have deleted most of dependencies, so it's just fullPage.js + 300 lines of css, still breaking on iPhone, sometimes I can scroll few slides then it tries to refresh the page when trying to swipe and then showing Can't open this page error...

**Comment by alvarotrigo** [comment]
If you remove those extra 300 lines of CSS, it works just fine, right?

Probably the easiest way to find out what's the cause of the problem is by reducing those 300 lines bit by bit until you find what it can be :)

**Comment by kovinet** [comment]
I found that if I delete these lines:

```css
.text {
    padding: 80px;
    width: 100%;
    max-width: 1000px;
    margin: 0 auto;
}
.text h1 {
    font-size: 2.5rem;
    font-weight: 300;
    line-height: 1.2;
    margin-top: 0;
    margin-bottom: 50px;
}

.text h2 {
    font-size: 2rem;
    font-weight: 300;
    line-height: 1.2;
    margin-top: 0;
    margin-bottom: 50px;
}

.text h3 {
    font-size: 20px;
    font-weight: 300;
    line-height: 1.2;
    text-transform: uppercase;
    margin-top: 50px;
    margin-bottom: 30px;
}
```

Then it works better, it still crashes, but after 3 or 4 sections instead after first attempt to slide.
But this is very basic CSS and it doens't make any sense why it is causing it :)

I will continue tomorrow when I have access to someone with affected phone ...
