### ISSUE TITLE
Fixed elements within fullpage.js selected sections

### ISSUE THREAD

**Issue by Cacolo21** [alvarotrigo/fullPage.js#4615]
Hey all. First time playing with fullpage.js and so far so good.

I'm not a coder, but getting there slowly. I need some elements to have position fixed from 2nd to 5th section within fullpage. Kind of like on the homepage of lag.eu/en. If anyone can point me in the right direction, please do.

Placing fixed elements outside of the fullpage with initial display:none turned into display:fixed once the 2nd section is reached works. But I want the fixed element to only become fixed when 2nd section is loaded, just like at lag.eu/en. Thanks.

**Comment by alvarotrigo** [comment]
This is more a CSS question than a fullPage.js one :)

But taking a look at the page you provided, it seems they use `is-fixed` to fix the menu on the left, and then they remove it, probably using the `beforeLeave` callback whenever they need. 

Then adding it again using `afterLoad`.
Try trick here is to add the fixed (or "static") element on the section that will trigger the change of state. In this case after moving to section 3 the fixed element will not be fixed anymore, so then we include the fixed element within the 2nd section. 

Here's my try on it:
https://codepen.io/alvarotrigo/pen/MWRXVwM

HTML
```html
<div id="fullpage">
    <div class="section">Section 1
    </div>
    <div class="section">
        Section 2
      <div class="box is-fixed"></div>
    </div>
    <div class="section"> 
      <p>
        <h2>Section 3</h2>
      </p>
    </div>
 <div class="section"> 
      <p>
        <h2>Section 4</h2>
      </p>
    </div>
</div>
``` 


CSS
```css
.section {
  text-align:center;
  font-size: 3em;
}
.fp-section{
  position:relative;
}
.box{
  display: block;
  width: 200px;
  height: 200px;
  background: red;
  z-index:999;
  position: absolute;
  top: 20px;
  left: 20px;
}
.is-fixed{
  position: fixed;
  top: 20px;
  left: 20px;
}
``` 

JS
```js
new fullpage('#fullpage', {
  sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
  
  // required for "fixed" elements to work
  scrollBar: true,
  
  beforeLeave: function(origin, destination, direction, trigger){
    if(destination.index >= 2){
      document.querySelector('.box').classList.remove('is-fixed')
    }
  },
  
  afterLoad: function(origin, destination, direction, trigger){
    if(destination.index < 2){
      document.querySelector('.box').classList.add('is-fixed')
    }
  },

  
  // Get your license at https://alvarotrigo.com/fullPage/pricing/
  licenseKey: 'YOUR LICENSE KEY HERE '
});
```

I hope that helps!
