### ISSUE TITLE
position:fixed elements don't stay fixed

### ISSUE THREAD

**Issue by Lezuzius83** [alvarotrigo/fullPage.js#4700]
I want the hamburger menu on the top right corner of the site (https://kadar-kocka-felujitas.hu/) to stay fixed when scrolling.
It is set to fixed position, but get scrolled with the rest of the section.
If I give it a CSS ID and add that ID to the Design / Fixed elements section, the whole hamburger menu disappeares instead of being fixed in place.

**Comment by alvarotrigo** [comment]
You'll have to use the Fixed Elements option and put in there the selector for your menu, in this case `#hambi`:
https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/docs/#fixed-elements

**Comment by alvarotrigo** [comment]
To make it look the same you might need to apply some extra CSS:

```css
#hambi{
    z-index: 999999;
    right: 160px;
    top: 70px;
    position: fixed;
}
#hambi img{ 
      width: 55px;
      height: 55px;
}
```
