### ISSUE TITLE
Console error when hiding 1st section

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/fullPage.js#4701]
There's a console error on when adding the following CSS to the [demo page ](https://alvarotrigo.com/fullPage/#page1):

```css
@media (min-width: 768px) and (max-width:880px) {
    #section-1 {
        display: none;
    }
}
```
I think it only happens when the first section is being viewed.

![Image](https://github.com/user-attachments/assets/7b26f8d8-9e85-4549-9057-42f7702e6eb7)

With [default demo page](https://alvarotrigo.com/fullPage/#page1)
![Image](https://github.com/user-attachments/assets/ce714757-dd7e-4691-993c-7628f1156295)
