### ISSUE TITLE
Float doesn't work

### ISSUE THREAD

**Issue by gerardox** [alvarotrigo/fullPage.js#636]
Hi everybody, 

I think my question is rather trivial, but after fruitless reading of all of the closed issues and google results this is my last resort: I just want to integrate pictures with floating text or a initial with dropcap like this: 

``` css
.dropcap {
            font-size: 4.6em;   
            line-height: 0.8em;
            float: left;
            font-family: Serif;    
            font-weight: bold;
            position: relative;
            left: -3px;
        } 
```
- but it doesn't work in fullpage.js. Anyone knows help?

Needless to say that fullpage.js is really brilliant tool and that I'm very thankful that Alvaro Trigo provided it. 

Thanks!

Cheers
Gerox
