### ISSUE TITLE
Turn off the slimScroll on fullpage js

### ISSUE THREAD

**Issue by sumesh1234** [alvarotrigo/fullPage.js#976]
Hi,
How to turn off the slimScroll on fullpage js. because i like to go with the browser default scrollbar.

**Comment by alvarotrigo** [comment]
The plugin doesn't provide such an option. 
If you really need it, I could customize the plugin for you for some price. Just [contact me](http://alvarotrigo.com/#contact-page) if so.

**Comment by alvarotrigo** [comment]
If you just want to change the appearence of the scroll bar, this would do the trick:

```css
.slimScrollBar {
    display: none !important;
}
.fp-scrollable {
    overflow: auto !important;
}
```

Using `scrollOverflow:true`.
