### ISSUE TITLE
why navigationColor is not working ？

### ISSUE THREAD

**Issue by mnotw** [alvarotrigo/fullPage.js#994]
I'm using the 2.5.6 version

what am I doing wrong ?
```javascript
    $('#dkt').fullpage({
        verticalCentered: false,
        css3: true,
        sectionsColor: ['#00254C', '#F0F0F0','#3AAC8A', '#F8F8F8'],
        anchors: ['page1', 'page2', 'page3', 'page4'],
        navigation: true,
        navigationColor:'#F0C869',
        navigationPosition: 'right',
        onLeave: function(index, nextIndex, direction){
        			if(index == 4){
        				$("#video_pop_layer,.video_pop_container").hide();
        			}
        		}
    });
```

**Comment by alvarotrigo** [comment]
Yep, that's a bug. 
The option was removed from the docs time ago, as you'd better deal with CSS for it, but I'll take a look for the next version.

Thanks for reporting it.

**Comment by alvarotrigo** [comment]
Won't be solved. It is not simple to deal with the `active` bullet by using inline styles.
The option will be deleted from the source code as well. 

In order to change the color (background and border) you should deal with the CSS and overwrite this styles with your own colors:

```css
#fp-nav ul li a.active span,
.fp-slidesNav ul li a.active span {
    background: #333;
}
#fp-nav ul li a span,
.fp-slidesNav ul li a span {
    top: 2px;
    left: 2px;
    width: 8px;
    height: 8px;
    border: 1px solid #000;
    background: rgba(0, 0, 0, 0);
    border-radius: 50%;
    position: absolute;
    z-index: 1;
}
```
